name: itecotesttask
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  auto_route: ^10.1.0+1
  talker: ^5.0.0
  talker_flutter: ^5.0.0
  talker_bloc_logger: ^5.0.0
  talker_dio_logger: ^5.0.0
  cached_network_image: ^3.4.1
  get_it: ^8.2.0
  dio: ^5.9.0
  json_annotation: any
  cupertino_icons: ^1.0.8
  bloc: any

dev_dependencies:
  flutter_native_splash: ^2.4.0
  build_runner: ^2.5.4
  auto_route_generator: ^10.2.3
  json_serializable: ^6.9.5
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/splash/
    - assets/images/onboarding/
  uses-material-design: true
flutter_native_splash:
  color: "#006C51"
  image: assets/images/splash/splash.png

  android: true
  ios: true

  android_12:
    image: assets/images/splash/splash12.png
    icon_background_color: "#006C51"